# Generated by Django 5.0.3 on 2024-03-06 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codesnippet',
            name='content',
            field=models.TextField(default=1),
        ),
    ]
