# Generated by Django 5.0.3 on 2024-03-06 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_codesnippet_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codesnippet',
            name='id',
        ),
        migrations.AddField(
            model_name='codesnippet',
            name='code_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
