# Generated by Django 5.0.3 on 2024-03-11 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_latestupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codesnippet',
            name='code_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
